#!/usr/bin/env bash
set -euo pipefail

REPO="rodionlim/portfolio-manager-go"
APP_NAME="portfolio-manager"
INSTALL_DIR="${PORTFOLIO_MANAGER_HOME:-$HOME/portfolio-manager}"

usage() {
  cat <<EOF
Portfolio Manager installer

Usage:
  curl -fsSL https://raw.githubusercontent.com/${REPO}/main/scripts/install.sh | bash
  curl -fsSL https://raw.githubusercontent.com/${REPO}/main/scripts/install.sh | bash -s -- --run
  curl -fsSL https://raw.githubusercontent.com/${REPO}/main/scripts/install.sh | bash -s -- --daemon

Environment:
  PORTFOLIO_MANAGER_HOME  Install directory. Defaults to ~/portfolio-manager.

Options:
  --run                   Start Portfolio Manager after installation. This is the default.
  --no-run                Install only; do not start Portfolio Manager.
  --daemon                Install and start a macOS LaunchAgent or Linux systemd user service.
  --no-prompts            Skip optional environment variable prompts.
  -h, --help              Show this help.
EOF
}

RUN_AFTER_INSTALL=1
INSTALL_DAEMON=0
PROMPT_ENV=1
while [[ $# -gt 0 ]]; do
  case "$1" in
    --run)
      RUN_AFTER_INSTALL=1
      shift
      ;;
    --no-run)
      RUN_AFTER_INSTALL=0
      shift
      ;;
    --daemon)
      INSTALL_DAEMON=1
      RUN_AFTER_INSTALL=0
      shift
      ;;
    --no-prompts)
      PROMPT_ENV=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

download() {
  local url="$1"
  local output="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fL --progress-bar -o "$output" "$url"
  elif command -v wget >/dev/null 2>&1; then
    wget -q --show-progress -O "$output" "$url"
  else
    echo "Missing required command: curl or wget" >&2
    exit 1
  fi
}

env_file_value() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

prompt_optional_env() {
  ENV_FILE="${INSTALL_DIR}/${APP_NAME}.env"
  GEMINI_API_KEY_VALUE=""
  ANALYTICS_SCHEDULE_VALUE=""

  if [[ "$PROMPT_ENV" -ne 1 || ! -r /dev/tty || ! -w /dev/tty ]]; then
    return
  fi

  echo
  echo "Optional settings. Press Enter to skip any value." >/dev/tty
  printf "Gemini API key (optional, used for analytics): " >/dev/tty
  IFS= read -r GEMINI_API_KEY_VALUE </dev/tty || GEMINI_API_KEY_VALUE=""
  printf "Analytics schedule cron [0 17 * * 1]: " >/dev/tty
  IFS= read -r ANALYTICS_SCHEDULE_VALUE </dev/tty || ANALYTICS_SCHEDULE_VALUE=""

  if [[ -z "$GEMINI_API_KEY_VALUE" && -z "$ANALYTICS_SCHEDULE_VALUE" ]]; then
    rm -f "$ENV_FILE"
    echo "No optional environment variables configured."
    return
  fi

  {
    echo "# Portfolio Manager environment"
    echo "# Generated by scripts/install.sh"
    if [[ -n "$GEMINI_API_KEY_VALUE" ]]; then
      printf "GEMINI_API_KEY=%s\n" "$(env_file_value "$GEMINI_API_KEY_VALUE")"
    fi
    if [[ -n "$ANALYTICS_SCHEDULE_VALUE" ]]; then
      printf "ANALYTICS_SCHEDULE=%s\n" "$(env_file_value "$ANALYTICS_SCHEDULE_VALUE")"
    fi
  } >"$ENV_FILE"
  chmod 600 "$ENV_FILE"

  echo "Saved optional environment variables to:"
  echo "  ${ENV_FILE}"
}

load_env_file() {
  if [[ -f "${ENV_FILE:-}" ]]; then
    set -a
    # shellcheck disable=SC1090
    . "$ENV_FILE"
    set +a
  fi
}

install_linux_service() {
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "systemctl not found; cannot install Linux user service." >&2
    exit 1
  fi

  local user_unit_dir="${HOME}/.config/systemd/user"
  local unit_file="${user_unit_dir}/${APP_NAME}.service"
  mkdir -p "$user_unit_dir"

  cat >"$unit_file" <<EOF
[Unit]
Description=Portfolio Manager
After=network-online.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/${APP_NAME}
Restart=on-failure
RestartSec=5
EnvironmentFile=-${ENV_FILE}

[Install]
WantedBy=default.target
EOF

  systemctl --user daemon-reload
  systemctl --user enable --now "${APP_NAME}.service"

  echo "Portfolio Manager service started."
  echo "Status:"
  echo "  systemctl --user status ${APP_NAME}.service"
  echo "Logs:"
  echo "  journalctl --user -u ${APP_NAME}.service -f"
}

xml_escape() {
  local value="$1"
  value="${value//&/&amp;}"
  value="${value//</&lt;}"
  value="${value//>/&gt;}"
  value="${value//\"/&quot;}"
  printf "%s" "$value"
}

write_launchd_env() {
  local key="$1"
  local value="$2"
  if [[ -n "$value" ]]; then
    printf '      <key>%s</key>\n' "$(xml_escape "$key")"
    printf '      <string>%s</string>\n' "$(xml_escape "$value")"
  fi
}

install_macos_service() {
  local label="com.portfolio-manager.app"
  local plist_dir="${HOME}/Library/LaunchAgents"
  local plist_file="${plist_dir}/${label}.plist"
  mkdir -p "$plist_dir"

  cat >"$plist_file" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${INSTALL_DIR}/${APP_NAME}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${INSTALL_DIR}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${INSTALL_DIR}/${APP_NAME}.out.log</string>
  <key>StandardErrorPath</key>
  <string>${INSTALL_DIR}/${APP_NAME}.err.log</string>
EOF

  if [[ -n "$GEMINI_API_KEY_VALUE" || -n "$ANALYTICS_SCHEDULE_VALUE" ]]; then
    {
      echo "  <key>EnvironmentVariables</key>"
      echo "  <dict>"
      write_launchd_env "GEMINI_API_KEY" "$GEMINI_API_KEY_VALUE"
      write_launchd_env "ANALYTICS_SCHEDULE" "$ANALYTICS_SCHEDULE_VALUE"
      echo "  </dict>"
    } >>"$plist_file"
  fi

  cat >>"$plist_file" <<EOF
</dict>
</plist>
EOF

  launchctl bootout "gui/${UID}" "$plist_file" >/dev/null 2>&1 || true
  launchctl bootstrap "gui/${UID}" "$plist_file"
  launchctl enable "gui/${UID}/${label}"

  echo "Portfolio Manager LaunchAgent started."
  echo "Status:"
  echo "  launchctl print gui/${UID}/${label}"
  echo "Logs:"
  echo "  tail -f ${INSTALL_DIR}/${APP_NAME}.out.log ${INSTALL_DIR}/${APP_NAME}.err.log"
}

install_daemon() {
  local os
  os="$(uname -s)"

  case "$os" in
    Linux)
      install_linux_service
      ;;
    Darwin)
      install_macos_service
      ;;
    *)
      echo "Daemon install is currently supported on macOS and Linux only." >&2
      exit 1
      ;;
  esac
}

detect_asset() {
  local os
  local arch
  os="$(uname -s)"
  arch="$(uname -m)"

  case "${os}:${arch}" in
    Darwin:arm64|Darwin:aarch64)
      echo "portfolio-manager_darwin_arm64"
      ;;
    Linux:x86_64|Linux:amd64)
      echo "portfolio-manager_linux_amd64"
      ;;
    *)
      echo "Unsupported platform: ${os} ${arch}" >&2
      echo "Download a matching asset manually from https://github.com/${REPO}/releases/latest" >&2
      exit 1
      ;;
  esac
}

main() {
  need_cmd uname
  need_cmd mkdir
  need_cmd chmod

  local asset
  local url
  local binary
  asset="$(detect_asset)"
  url="https://github.com/${REPO}/releases/latest/download/${asset}"
  binary="${INSTALL_DIR}/${APP_NAME}"

  echo "Installing Portfolio Manager into ${INSTALL_DIR}"
  mkdir -p "$INSTALL_DIR"
  download "$url" "$binary"
  chmod +x "$binary"

  if command -v xattr >/dev/null 2>&1; then
    xattr -d com.apple.quarantine "$binary" 2>/dev/null || true
  fi

  echo
  echo "Portfolio Manager installed:"
  echo "  ${binary}"
  echo
  echo "Start it with:"
  echo "  cd ${INSTALL_DIR}"
  echo "  ./portfolio-manager"
  echo
  echo "Default URLs:"
  echo "  Backend: http://localhost:8080"
  echo "  MCP:     http://localhost:8081/mcp"
  echo
  echo "To keep Portfolio Manager running in the background on macOS or Linux:"
  echo "  curl -fsSL https://raw.githubusercontent.com/${REPO}/main/scripts/install.sh | bash -s -- --daemon"

  prompt_optional_env

  if [[ "$INSTALL_DAEMON" -eq 1 ]]; then
    echo
    echo "Installing Portfolio Manager as a background service..."
    install_daemon
    return
  fi

  if [[ "$RUN_AFTER_INSTALL" -eq 1 ]]; then
    echo
    echo "Starting Portfolio Manager..."
    cd "$INSTALL_DIR"
    load_env_file
    exec ./portfolio-manager
  fi
}

main
