name: Release

on:
  workflow_dispatch: # Trigger workflow manually

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SWAG_VERSION: v1.16.4
      GO_VERSION: 1.23.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.2"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@${{ env.SWAG_VERSION }}

      - name: Build release
        run: make assets-compress build BUILTIN_ASSETS=1

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-manager
          path: ./portfolio-manager
