name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  call-reusable-release:
    if: github.event.pull_request.merged && !github.event.pull_request.head.repo.fork
    uses: ./.github/workflows/release-reusable.yml
    secrets: inherit
